name: CI
on:
  push:
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest
    if: "startsWith(github.ref, 'refs/tags/') || !contains(github.event.head_commit.message, '[skip ci]')"
    env:
      PLATFORM: x64
      WIRESHARK_LIB_DIR: C:/wireshark-win64-libs-4.0
      GLIB_DIR: C:/wireshark-win64-libs-4.0/vcpkg-export-20220726-1-win64ws/installed/x64-windows
      WIRESHARK_DIR: ${{ github.workspace }}/wireshark
      WIRESHARK_BUILD_DIR: ${{ github.workspace }}/wireshark/build
      WIRESHARK_DIR_LIB: ${{ github.workspace }}/wireshark/build/run/RelWithDebInfo
      WIRESHARK_LIB: ${{ github.workspace }}/wireshark/build/run/RelWithDebInfo/wireshark.lib
      WSUTIL_LIB: ${{ github.workspace }}/wireshark/build/run/RelWithDebInfo/wsutil.lib
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          path: dissector
      - name: Checkout Wireshark
        uses: actions/checkout@v2
        with:
          repository: wireshark/wireshark
          path: wireshark
          ref: wireshark-4.0.6
      - name: Choco install Wireshark Deps
        run: choco install -y --no-progress cmake winflexbison3 strawberryperl asciidoctorj xsltproc docbook-bundle make mingw
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        with:
          vs-version: 16.4
      - name: Make build dir
        run: mkdir build
        working-directory: wireshark
      - name: Configure Wireshark
        run: cmake -A x64 .. -DBUILD_wireshark=OFF
        working-directory: wireshark/build
      - run: cmake --build . --config RelWithDebInfo --target epan
        working-directory: wireshark/build
      - name: Configure dissector (Debug)
        if: "!startsWith(github.ref, 'refs/tags/') || contains(github.ref, 'beta')"
        run: cmake -S . -G Ninja -B build
        working-directory: dissector
      - name: Configure dissector (Release)
        if: "startsWith(github.ref, 'refs/tags/') && !contains(github.ref, 'beta')"
        run: cmake -DCMAKE_BUILD_TYPE=Release -S . -G Ninja -B build
        working-directory: dissector
      - name: Build dissector
        run: cmake --build build --target MC_Dissector
        working-directory: dissector
      - name: Upload dissector
        uses: actions/upload-artifact@v2
        with:
          name: windows
          path: dissector/build/mcdissector.dll

  publish:
    needs: [ build-windows ]
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/')"
    steps:
      - name: Download windows artifact
        uses: actions/download-artifact@v2
        with:
          name: windows
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: ${{ contains(github.ref, 'beta') }}
      - name: Upload mcdissector.dll
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./mcdissector.dll
          asset_name: mcdissector.dll
          asset_content_type: application/octet-stream
