name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      PLATFORM: x64
      WIRESHARK_LIB_DIR: C:/wireshark-win64-libs-4.0
      GLIB_DIR: C:/wireshark-win64-libs-4.0/vcpkg-export-20220726-1-win64ws/installed/x64-windows
      WIRESHARK_DIR: ${{ github.workspace }}/wireshark
      WIRESHARK_BUILD_DIR: ${{ github.workspace }}/wireshark/build
      WIRESHARK_DIR_LIB: ${{ github.workspace }}/wireshark/build/run/RelWithDebInfo/wireshark.lib
      WIRESHARK_LIB: ${{ github.workspace }}/wireshark/build/run/RelWithDebInfo/wireshark.lib
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          path: dissector
      - name: Checkout Wireshark
        uses: actions/checkout@v2
        with:
          repository: wireshark/wireshark
          path: wireshark
          ref: wireshark-4.0.6
      - name: Choco install Wireshark Deps
        run: choco install -y --no-progress cmake winflexbison3 strawberryperl asciidoctorj xsltproc docbook-bundle make mingw
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        with:
          vs-version: 16.4
      - name: Make build dir
        run: mkdir build
        working-directory: wireshark
      - run: cmake -A x64 .. -DBUILD_wireshark=OFF
        working-directory: wireshark/build
      - run: cmake --build . --config RelWithDebInfo --target epan
        working-directory: wireshark/build
      - name: Build dissector
        run: cmake -S . -B build
        working-directory: dissector
      - name: Upload dissector
        uses: actions/upload-artifact@v2
        with:
          name: windows
          path: dissector/build/*.dll

